version: "2"

services:
  database:
    image: mysql/mysql-server:5.6
    volumes:
      - ./docker/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: msdoc
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database
    restart: always
    hostname: msdoc_webapp
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/site/
   
